// const PDFDocument = require('pdfkit');

// const generatePDF = (doc_data, type = 'Invoice') => {
//   const doc = new PDFDocument({ margin: 50, size: 'A4' });

//   // Header bar
//   doc.rect(0, 0, doc.page.width, 80).fill('#1E40AF');
//   doc.fillColor('white').fontSize(24).font('Helvetica-Bold')
//     .text('MANGALYOG ENTERPRISE', 50, 22);
//   doc.fontSize(11).font('Helvetica')
//     .text('Billing & Site Management', 50, 52);

//   doc.fillColor('black');

//   // Document number
//   const docNum = type === 'Invoice' ? doc_data.invoice_number : doc_data.quotation_number;
//   doc.moveDown(2);
//   doc.fontSize(20).font('Helvetica-Bold').text(type.toUpperCase(), { align: 'right' });
//   doc.fontSize(11).font('Helvetica').text(`#${docNum}`, { align: 'right' });
//   doc.moveDown();

//   // Site info
//   const site = doc_data.site || {};
//   doc.fontSize(11).font('Helvetica-Bold').text('Billed To:');
//   doc.font('Helvetica').fontSize(10)
//     .text(site.name || 'N/A')
//     .text(site.address || '')
//     .text(site.owner_name ? `Owner: ${site.owner_name}` : '')
//     .text(site.phone      ? `Phone: ${site.phone}`      : '')
//     .text(site.gst_number ? `GST: ${site.gst_number}`   : '');

//   doc.moveDown();

//   // Meta info
//   doc.fontSize(10).font('Helvetica')
//     .text(`Date: ${new Date(doc_data.date).toLocaleDateString('en-IN')}`,   { align: 'right' })
//     .text(`Due / Valid: ${doc_data.due_date || doc_data.valid_until
//       ? new Date(doc_data.due_date || doc_data.valid_until).toLocaleDateString('en-IN')
//       : 'N/A'}`, { align: 'right' })
//     .text(`Status: ${(doc_data.status || '').toUpperCase()}`, { align: 'right' });

//   doc.moveDown();

//   // Items table
//   const tableTop = doc.y;
//   const col = { desc: 50, qty: 290, rate: 360, amount: 460 };

//   doc.rect(50, tableTop, doc.page.width - 100, 22).fill('#1E40AF');
//   doc.fillColor('white').fontSize(10).font('Helvetica-Bold')
//     .text('Description', col.desc + 4, tableTop + 5)
//     .text('Qty',         col.qty,      tableTop + 5)
//     .text('Rate',        col.rate,     tableTop + 5)
//     .text('Amount',      col.amount,   tableTop + 5);

//   doc.fillColor('black');
//   let rowY = tableTop + 28;

//   (doc_data.items || []).forEach((item, i) => {
//     const bg = i % 2 === 0 ? '#F1F5F9' : '#FFFFFF';
//     doc.rect(50, rowY - 4, doc.page.width - 100, 20).fill(bg);
//     doc.fillColor('black').font('Helvetica').fontSize(10)
//       .text(item.description,                      col.desc + 4, rowY, { width: 230 })
//       .text(String(item.quantity),                 col.qty,      rowY)
//       .text(`Rs.${parseFloat(item.rate).toLocaleString('en-IN')}`,   col.rate,   rowY)
//       .text(`Rs.${parseFloat(item.amount).toLocaleString('en-IN')}`, col.amount, rowY);
//     rowY += 24;
//   });

//   doc.moveDown(2);

//   // Totals
//   doc.font('Helvetica').fontSize(10)
//     .text(`Subtotal: Rs.${parseFloat(doc_data.subtotal || 0).toLocaleString('en-IN')}`, { align: 'right' })
//     .text(`Tax (${doc_data.tax_rate || 0}%): Rs.${parseFloat(doc_data.tax_amount || 0).toLocaleString('en-IN')}`, { align: 'right' });

//   doc.font('Helvetica-Bold').fontSize(13)
//     .text(`Total: Rs.${parseFloat(doc_data.total).toLocaleString('en-IN')}`, { align: 'right' });

//   if (doc_data.notes) {
//     doc.moveDown();
//     doc.font('Helvetica-Bold').fontSize(10).text('Notes:');
//     doc.font('Helvetica').fontSize(10).text(doc_data.notes);
//   }

//   // Footer
//   doc.fontSize(9).fillColor('grey')
//     .text('Generated by Mangalyog Enterprise', 50, doc.page.height - 50, { align: 'center' });

//   return doc;
// };

// module.exports = { generatePDF };
const PDFDocument = require('pdfkit');

/* ---------- Helpers ---------- */
function fmtNum(n) {
  return Number(n || 0).toLocaleString('en-IN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  });
}

function fmtDate(d) {
  if (!d) return 'N/A';
  const dt = new Date(d);
  return `${dt.getDate()}-${dt.getMonth() + 1}-${dt.getFullYear()}`;
}

function numberToWords(num) {
  const a = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
    'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen'];
  if (num < 16) return a[num];
  return num.toString(); // keep simple
}

/* ---------- Main Function ---------- */
const generatePDF = (doc_data, type = 'Invoice') => {
  const doc = new PDFDocument({ margin: 0, size: 'A4' });

  const PW = doc.page.width;
  const PH = doc.page.height;
  const L = 36;
  const R = PW - 36;

  drawHeader(doc, doc_data, type, PW, PH, L, R);
  const y = drawToFrom(doc, doc_data, L, R);
  drawTable(doc, doc_data, y + 10, L, R);

  return doc;
};

/* ---------- Header ---------- */
function drawHeader(doc, data, type, PW, PH, L, R) {
  doc.rect(0, 0, PW, 10).fill('#EA580C');

  const T = 18;

  doc.font('Helvetica-Bold').fontSize(14)
    .text('MANGALYOG ENTERPRISE', L, T);

  doc.font('Helvetica').fontSize(9)
    .text('Billing & Site Management', L, T + 18);

  const docNum = type === 'Invoice'
    ? data.invoice_number
    : data.quotation_number;

  doc.text(`DATE - ${fmtDate(data.date)}`, R - 200, T, { align: 'right' });

  doc.text(`${type.toUpperCase()} NO. ${docNum}`, R - 200, T + 25, { align: 'right' });

  doc.moveTo(L, 100).lineTo(R, 100).stroke();

  doc.rect(0, PH - 10, PW, 10).fill('#EA580C');
}

/* ---------- To / From ---------- */
function drawToFrom(doc, data, L, R) {
  const site = data.site || {};
  const startY = 110;

  doc.font('Helvetica-Bold').text('TO:', L, startY);
  doc.font('Helvetica')
    .text(site.name || '', L, startY + 15)
    .text(site.address || '', L, startY + 30);

  doc.font('Helvetica-Bold').text('FROM:', R - 220, startY);
  doc.font('Helvetica')
    .text('Mangalyog Enterprise', R - 220, startY + 15)
    .text('Solapur, Maharashtra', R - 220, startY + 30);

  return startY + 70;
}

/* ---------- Table ---------- */
function drawTable(doc, data, tableTop, L, R) {
  const items = data.items || [];

  const col = {
    sr: L,
    desc: L + 40,
    qty: L + 300,
    rate: L + 360,
    amt: L + 450
  };

  const headerH = 25;
  const rowH = 25;

  /* PASS 1 - Fill */
  doc.rect(L, tableTop, R - L, headerH).fill('#E8E8E8');

  /* PASS 2 - Lines */
  doc.moveTo(L, tableTop).lineTo(R, tableTop).stroke();
  doc.moveTo(L, tableTop + headerH).lineTo(R, tableTop + headerH).stroke();

  /* PASS 3 - Header Text */
  doc.fillColor('black').font('Helvetica-Bold').fontSize(10)
    .text('#', col.sr + 5, tableTop + 8)
    .text('Description', col.desc, tableTop + 8)
    .text('Qty', col.qty, tableTop + 8)
    .text('Rate', col.rate, tableTop + 8)
    .text('Amount', col.amt, tableTop + 8);

  let y = tableTop + headerH;

  items.forEach((item, i) => {
    if (i % 2 === 1) {
      doc.rect(L, y, R - L, rowH).fill('#F7F7F7');
    }

    doc.fillColor('black').font('Helvetica').fontSize(10)
      .text(i + 1, col.sr + 5, y + 8)
      .text(item.description, col.desc, y + 8)
      .text(item.quantity, col.qty, y + 8)
      .text(fmtNum(item.rate), col.rate, y + 8)
      .text(fmtNum(item.amount), col.amt, y + 8);

    y += rowH;
  });

  /* Totals */
  doc.moveDown();

  doc.font('Helvetica')
    .text(`Subtotal: ${fmtNum(data.subtotal)}`, R - 200, y + 10, { align: 'right' })
    .text(`Tax (${data.tax_rate || 0}%): ${fmtNum(data.tax_amount)}`, R - 200, y + 25, { align: 'right' });

  doc.font('Helvetica-Bold').fontSize(12)
    .text(`Total: ${fmtNum(data.total)}`, R - 200, y + 45, { align: 'right' });

  /* In Words */
  doc.moveDown();
  doc.font('Helvetica-Bold').text('In Words:', L, y + 70);
  doc.font('Helvetica')
    .text(numberToWords(Math.floor(data.total)) + ' Rupees Only', L + 80, y + 70);

  /* Notes */
  if (data.notes) {
    doc.moveDown();
    doc.font('Helvetica-Bold').text('Notes:', L, y + 100);
    doc.font('Helvetica').text(data.notes, L, y + 115);
  }
}

module.exports = { generatePDF };